#!/usr/bin/env bash
# ==============================================================================
# sync-omp-providers.sh — 从 opencode 配置同步 provider 到 oh-my-pi
#
# 功能:
#   1. 读取 ~/.config/opencode/opencode.json 中的 provider 列表
#   2. 生成 ~/.omp/agent/models.yml（API Key 自动脱敏，仅保留首尾字符）
# 注意: 会覆盖 omp 现有 provider 配置，如需保留请手动合并
# ==============================================================================
set -euo pipefail

OPENCODE_CONFIG="${HOME}/.config/opencode/opencode.json"
OMP_CONFIG="${HOME}/.omp/agent/models.yml"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { printf "${CYAN}[INFO]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*"; }

# --- 检查依赖 ---
if ! command -v jq &>/dev/null; then
  error "jq is required. Install it first: brew install jq / apt install jq"
  exit 1
fi

if [ ! -f "$OPENCODE_CONFIG" ]; then
  error "opencode config not found at $OPENCODE_CONFIG"
  exit 1
fi

# --- 读取 opencode 配置并去除注释（JSONC 兼容） ---
clean_json=$(python3 -c "
import json, re, sys
with open('$OPENCODE_CONFIG') as f:
    text = f.read()
# 去除单行注释（保留字符串内的 //）
result = []
i = 0
in_str = False
str_char = None
while i < len(text):
    ch = text[i]
    if in_str:
        result.append(ch)
        if ch == '\\\\' and i + 1 < len(text):
            i += 1
            result.append(text[i])
        elif ch == str_char:
            in_str = False
            str_char = None
    elif ch in ('\"', \"'\"):
        in_str = True
        str_char = ch
        result.append(ch)
    elif ch == '/' and i + 1 < len(text) and text[i+1] == '/':
        while i < len(text) and text[i] != '\n':
            i += 1
        result.append('\n')
        continue
    else:
        result.append(ch)
    i += 1
sys.stdout.write(''.join(result))
")
if ! echo "$clean_json" | jq '.' > /dev/null 2>&1; then
  error "Failed to parse opencode config (invalid JSON)"
  exit 1
fi

# --- 读取 provider 列表 ---
providers=$(echo "$clean_json" | jq -r '.provider | keys[]' 2>/dev/null) || {
  error "Failed to extract providers from opencode config"
  exit 1
}

if [ -z "$providers" ]; then
  error "No providers found in opencode config"
  exit 1
fi

# --- 备份现有 omp 配置 ---
if [ -f "$OMP_CONFIG" ]; then
  bak="${OMP_CONFIG}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$OMP_CONFIG" "$bak"
  info "Backed up existing omp config → $bak"
fi

mkdir -p "$(dirname "$OMP_CONFIG")"

# --- 生成 YAML ---
{
  echo "# Generated by sync-omp-providers.sh on $(date +%Y-%m-%d)"
  echo "# API keys are masked for security. Fill in real keys in opencode config."
  echo ""
  echo "providers:"

  for provider in $providers; do
    name=$(echo "$clean_json" | jq -r ".provider[\"$provider\"].name // \"$provider\"")
    baseURL=$(echo "$clean_json" | jq -r ".provider[\"$provider\"].options.baseURL // \"\"")
    apiKey=$(echo "$clean_json" | jq -r ".provider[\"$provider\"].options.apiKey // \"\"")

    # 脱敏 API Key：保留首 4 位 + 末 4 位，中间用 * 填充
    if [ -z "$apiKey" ] || [ "$apiKey" = "null" ]; then
      masked="****"
    elif [ ${#apiKey} -le 8 ]; then
      masked="${apiKey:0:2}****${apiKey: -2}"
    else
      masked="${apiKey:0:4}****${apiKey: -4}"
    fi

    echo "  ${provider}:"
    echo "    name: ${name}"
    echo "    baseUrl: ${baseURL}"
    echo "    api: openai-completions"
    echo "    apiKey: \"${masked}\""
    echo "    authHeader: true"
    echo "    models:"

    # 读取模型列表
    model_ids=$(echo "$clean_json" | jq -r ".provider[\"$provider\"].models | keys[]" 2>/dev/null) || true
    if [ -n "$model_ids" ]; then
      for model_id in $model_ids; do
        model_name=$(echo "$clean_json" | jq -r ".provider[\"$provider\"].models[\"$model_id\"].name // \"$model_id\"")
        echo "      - id: ${model_id}"
        echo "        name: ${model_name}"
        echo "        reasoning: false"
        echo "        input: [text]"
      done
    fi
  done
} > "$OMP_CONFIG"

ok "Synced ${providers} providers from opencode → omp"
echo ""
info "Next steps:"
info "  1. Edit ${OMP_CONFIG} to fill in your real API keys"
info "  2. Test with: omp --list-models"
echo ""
