#!/usr/bin/env python3
"""sync-omp-providers — 从 opencode 配置同步 provider 到 oh-my-pi

功能:
  1. 读取 ~/.config/opencode/opencode.json 中的 provider 列表
  2. 生成 ~/.omp/agent/models.yml（包含完整的 API Key）
注意: 会覆盖 omp 现有 provider 配置，如需保留请手动合并
"""
import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path


OPENCODE_CONFIG = Path.home() / ".config" / "opencode" / "opencode.json"
OMP_CONFIG = Path.home() / ".omp" / "agent" / "models.yml"

CYAN = "\033[0;36m"
GREEN = "\033[0;32m"
NC = "\033[0m"


def info(msg):
    print(f"{CYAN}[INFO]{NC}  {msg}")


def ok(msg):
    print(f"{GREEN}[OK]{NC}    {msg}")


def error(msg, code=1):
    print(f"\033[0;31m[ERROR]{NC} {msg}", file=sys.stderr)
    sys.exit(code)


def strip_jsonc(text: str) -> str:
    """去除 JSON 中的单行注释（//...），保留字符串内的 //"""
    result = []
    i = 0
    in_str = False
    str_char = None
    while i < len(text):
        ch = text[i]
        if in_str:
            result.append(ch)
            if ch == "\\" and i + 1 < len(text):
                i += 1
                result.append(text[i])
            elif ch == str_char:
                in_str = False
                str_char = None
        elif ch in ('"', "'"):
            in_str = True
            str_char = ch
            result.append(ch)
        elif ch == "/" and i + 1 < len(text) and text[i + 1] == "/":
            while i < len(text) and text[i] != "\n":
                i += 1
            result.append("\n")
            continue
        else:
            result.append(ch)
        i += 1
    return "".join(result)


def yaml_value(value: str) -> str:
    """YAML 值格式化：需要引号则引起来"""
    if not value:
        return ""
    needs_quote = False
    try:
        value.encode("ascii")
    except UnicodeEncodeError:
        needs_quote = True
    if any(c in value for c in ":{}[]*,#&*!|>%@`'\"/\\"):
        needs_quote = True
    if needs_quote:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def generate_yaml(data: dict) -> str:
    """生成 OMP models.yml 内容"""
    lines = [
        f"# Generated by sync-omp-providers.sh on {datetime.now():%Y-%m-%d}",
        "# API keys are synced from opencode config",
        "",
        "providers:",
    ]

    provider_keys = sorted(data.get("provider", {}).keys())
    for provider_id in provider_keys:
        prov = data["provider"][provider_id]
        name = prov.get("name", provider_id)
        options = prov.get("options", {})
        base_url = options.get("baseURL", "")
        api_key = options.get("apiKey", "")
        models = prov.get("models", {})

        lines.append(f"  {provider_id}:")
        lines.append(f"    name: {yaml_value(name)}")
        lines.append(f"    baseUrl: {yaml_value(base_url)}")
        lines.append("    api: openai-completions")
        lines.append(f'    apiKey: "{api_key}"')
        lines.append("    authHeader: true")
        lines.append("    models:")

        for model_id in sorted(models.keys()):
            model = models[model_id]
            model_name = model.get("name", model_id)
            lines.append(f"      - id: {yaml_value(model_id)}")
            lines.append(f"        name: {yaml_value(model_name)}")
            lines.append("        reasoning: false")
            lines.append("        input: [text]")

    return "\n".join(lines) + "\n"


def main():
    if not OPENCODE_CONFIG.exists():
        error(f"opencode config not found at {OPENCODE_CONFIG}")

    with open(OPENCODE_CONFIG, encoding="utf-8") as f:
        raw = f.read()

    try:
        clean = strip_jsonc(raw)
        data = json.loads(clean)
    except json.JSONDecodeError as e:
        error(f"Failed to parse opencode config (invalid JSON): {e}")

    providers = data.get("provider")
    if not providers:
        error("No providers found in opencode config")

    provider_names = sorted(providers.keys())
    info(f"Found providers: {', '.join(provider_names)}")

    if OMP_CONFIG.exists():
        ts = datetime.now().strftime("%Y%m%d%H%M%S")
        bak = OMP_CONFIG.with_suffix(f".bak.{ts}")
        shutil.copy2(str(OMP_CONFIG), str(bak))
        info(f"Backed up existing omp config → {bak}")

    OMP_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    yaml_content = generate_yaml(data)
    with open(OMP_CONFIG, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    total_models = sum(len(p.get("models", {})) for p in providers.values())
    ok(f"Synced {len(provider_names)} providers, {total_models} models from opencode → omp")
    print()
    info("API keys are synced from opencode config")
    info("Test with: omp --list-models")
    print()


if __name__ == "__main__":
    main()
